### ISSUE TITLE
Registro con correo electrónico

### ISSUE THREAD

**Issue by javirogo** [decide-ganimedes-autenticacion/decide-ganimedes-autenticacion#12]
Añadir al registro de usuarios un nuevo atributo (correo electrónico), el cuál será único y servirá como identificador para asignar usuarios en el censo.

Del mismo modo, se podrá añadir otro atributo que sea la fecha de nacimiento. De esta manera se podrá limitar ciertas encuestas por edad.

En esta mejora se ha previsto inicialmente que participen los módulos de autenticación, censo y almacenamiento.

**Comment by davigldom** [comment]
Incidencia replicada al repositorio principal de Decide-Ganímedes, y asignada a los coordinadores de Almacenamiento y Censo.

**Comment by davigldom** [comment]
Después de todos los fallos solucionados respecto al cambio del "username" al "email", creo que podríamos cerrar ya esta incidencia, y volverla abrir en un futuro si vuelven a salir errores, aunque es bastante improbable, ya que todo se ha probado bastantes veces durante bastante tiempo.

**Comment by davigldom** [comment]
> Después de todos los fallos solucionados respecto al cambio del "username" al "email", creo que podríamos cerrar ya esta incidencia, y volverla abrir en un futuro si vuelven a salir errores, aunque es bastante improbable, ya que todo se ha probado bastantes veces durante bastante tiempo.

Como expuse en este comentario anterior, procedo a cerrar la incidencia ya que últimamente no se han reportado más errores con la autenticación mediante correo electrónico.
