### ISSUE TITLE
Obtener datos de Usuario

### ISSUE THREAD

**Issue by davigldom** [decide-ganimedes-autenticacion/decide-ganimedes-autenticacion#32]
**[Incidencia replicada desde el repositorio padre de Decide-Ganímedes](https://github.com/decide-ganimedes/decide-ganimedes/issues/30)**

### Módulos implicados
Autenticación.

### Estado actual de la funcionalidad y qué se va a mejorar
Con el objetivo de poder realizar estadísticas basadas en los perfiles de Usuario durante una votación en curso, se requiere el acceso a las mismas mediante la realización de una llamada a la API.

### Cómo se quiere mejorar y el motivo
Tal y como se hace referencia en la incidencia #10, principalemente se necesita acceso a los atributos con los que se puedan determinar el sexo y edad del votante. Cabe destacar que el principal interés es la obtención de estos datos sobre un conjunto y no de forma aislada. De implementarse de forma que se tuviera que acceder uno a uno sobre cada votante podría impactar en el número de llamadas y consecuentemente en el rendimiento.

### Resultado esperado
A partir de una lista de ids de usuarios, contar cuantos usuarios hay de tal edad o de tal sexo.

### Alternativas consideradas
Actualmente, no se han considerado alternativas para esta mejora.

### Información adicional
Como observación, creo que devolver un objeto de usuario serializado simple no sería una solución al problema, pues dentro de él se incluyen otros muchos datos de carácter sensible (p.e. contraseña).

**Comment by carmenJaraAlvarez** [comment]
Necesitaríamos un poco más de información de lo que necesitan. Entiendo que es un listado de todos los usuarios sin password y ellos manipulan? o quizas es una selección según parámetros que nos pasen?. Con el numero de usuarios es bastante si es este último caso?

**Comment by davigldom** [comment]
_Comentario replicado desde el repositorio principal de Decide-Ganímedes_

Se propone como solución al problema la creación de dos métodos, que dada una lista con ids de usuarios, realicen un recuento de sus edades y sus sexos respectivamente. De esta forma se evitaría la llamada repetitiva a la API por cada uno de los votantes y se obtendría el mismo resultado.

**Comment by carmenJaraAlvarez** [comment]
No entiendo entonces la necesidad de nuestro módulo si ya tienen la relación de usuarios. En este caso lo que habría es que preguntar directamente a store con las condiciones. He mirado si existe alguna relación en el proyecto, que nos sitúe como necesarios pero no lo veo.
![image](https://user-images.githubusercontent.com/44395689/50540606-25940100-0b95-11e9-9de8-1c3dd8a766e6.png)

**Comment by carmenJaraAlvarez** [comment]
@davigldom 
Se ha preparado un método post de conteo por sexo y una página de prueba para simular recibir datos como lista en la rama 'contador'. Necesitamos saber si el formato de lista de ids que vamos a recibir en la request es el mismo que estamos utilizando.
Ejemplo de datos recibidos utilizados:
                  lista : ['2','4']
También necesitamos saber como es el formato de la respuesta esperada.

**Comment by carmenJaraAlvarez** [comment]
Tras la puesta en común con el submódulo de visualización, se han efectuado cambios en el método, pasándose de post a get.  
Subimos una versión para pruebas de integración. Tiene una variable list fija que hay que comentar y descomentar la recogida de información del request:
![image](https://user-images.githubusercontent.com/44395689/50557843-43727a80-0ce9-11e9-9d92-4d97e2b3d2e6.png)

**Comment by davigldom** [comment]
Desde el módulo de Visualización no se han reportado errores de esta funcionalidad, por lo que estamos a la espera de que ellos cierren la incidencia en el repositorio padre de Decide-Ganímedes para cerrar esta incidencia.

**Comment by davigldom** [comment]
**[Comentario replicado desde el repositorio padre de Decide-Ganímedes](https://github.com/decide-ganimedes/decide-ganimedes/issues/30#issuecomment-452075084)**

Se ha revisado la solución implementada y es necesario su cambio. La actual versión parece funcionar de forma correcta, sin embargo no está preparada para soportar llamadas API (simplemente se espera que la respuesta sea el renderizado de una página web). Este requisito (definido desde el comienzo), es fundamental para su usabilidad desde módulos externos.

Como solución, se propone extender de la clase APIView y renombrar el método a get

**Comment by carmenJaraAlvarez** [comment]
Se modifica. Aunque no es indispensable, sería bueno en cualquier caso disponer del código del submódulo que hace la llamada para mayores pruebas.

**Comment by carmenJaraAlvarez** [comment]
Se cierra una vez se ha probado integrada.
