### ISSUE TITLE
Fecha de nacimiento de tipo DateTime

### ISSUE THREAD

**Issue by davigldom** [decide-ganimedes-autenticacion/decide-ganimedes-autenticacion#33]
_Incidencia replicada desde el repositorio principal de Decide-Ganímedes_

La fecha de nacimiento está especificada de tipo DateTime, por lo que se tiene que especificar una hora. Creo que no tiene mucho sentido y debería cambiarse a tipo Date (DateField).

**Comment by carmenJaraAlvarez** [comment]
Ha sido necesario su cambio en la funcionalidad añadida de #32, por lo que damos por concluida.
