### ISSUE TITLE
Creación User panel admin

### ISSUE THREAD

**Issue by davigldom** [decide-ganimedes-autenticacion/decide-ganimedes-autenticacion#34]
_Incidencia replicada desde el repositorio principal de Decide-Ganímedes_

__Descripción:__ La creación de un User desde el panel de admin de Django no es correcta. El campo _Password_ espera el hash de la contraseña en lugar de la propia contraseña en sí.

#### Pasos para reproducir el problema:
1. Acceder al formulario de creación de un User desde el panel de administración Django (/admin/authentication/user/add)
2. Introducir datos válidos en los campos necesarios. Por ejemplo:
* _Password:_ decide2018
* _Last login:_ Today, Now
* _User permissions:_ Añadir todas
* _Email:_ ana@gmail.com
* _Birthdate:_ 1997-12-15, Now
* _Sex:_ Non-binary
3. Guardar los cambios
4. Crear una votación y añadir este nuevo usuario al censo
5. Iniciar la votación
6. Intentar votar con las credenciales de este usuario

#### ¿Cuál es la salida esperada? ¿Qué se obtiene en cambio?
La salida esperada es la entrada en la cabina de votación. Se obtiene un diálogo en el que aparece _"Error: Bad Request"_.

#### ¿Qué versión del producto se está usando? ¿En qué sistema operativo?
La versión del producto es la actual, siendo el último commit el a076853776741ba24aa6bd86534528640dbdd9e4 . Se está utilizando bajo una máquina virtual con Ubuntu 18.04.1 LTS
#### Información adicional:
Si se prueba a reemplazar el texto del campo _Password:_ por el hash de la contraseña, se puede acceder a la votación sin problemas.

Hash de la contraseña de ejemplo: pbkdf2_sha256$100000$lCy2XPLl5Q3M$1UfakGSsXtH32bgJ+qVuw6XUy6UlP+yMXUhTJ/Cvi/k=

__Subsistema:__ autenticación

**Comment by carmenJaraAlvarez** [comment]
Se reproduce la secuencia y comprueba existencia del bug.
Pese a ser de baja prioridad al poder realizarse el alta de usuario desde la nueva funcionalidad signup #2, se decide abordar por si estuviese relacionada con el bug recuento de votos #35.

**Comment by carmenJaraAlvarez** [comment]
Se investiga en red, llegándose a la conclusión de que es necesario modificar admin.py en autenticación.
![image](https://user-images.githubusercontent.com/44395689/50421275-d1f48100-083d-11e9-9b83-c24e0335d530.png)

**Comment by carmenJaraAlvarez** [comment]
Pese a que la creación está funcionando, la edición de usuario lanza error desde el panel del administrador. Reabrimos Issue.
