### ISSUE TITLE
Recuento de votos

### ISSUE THREAD

**Issue by davigldom** [decide-ganimedes-autenticacion/decide-ganimedes-autenticacion#35]
**[Incidencia replicada desde el repositorio padre de Decide-Ganímedes](https://github.com/decide-ganimedes/decide-ganimedes/issues/36)**

### Módulos implicados
Autenticación.

### Descripción del error
Excepción al intentar realizar el recuento de votos de una votación.

### Pasos para reproducir el error
1. Acceder al formulario de creación de una Voting desde el panel de administración Django (/admin/voting/voting/add).
2. Introducir datos válidos en los campos necesarios. Por ejemplo:
**Name:** Votación de prueba.
**Question:** Seleccionar o crear una Question válida.
**Postproc type:** Identity.
**Auths:** Seleccionar o crear una Auth válida.
3. Guardar los cambios.
4. Añadir usuarios al censo de la votación que se acaba de crear.
5. Iniciar la votación (Start).
6. Votar con las credenciales de varios de los usuarios censados en la votación.
7. Parar la votación (Stop).
8. Realizar el recuento de votos de la votación (Tally).

### Resultado obtenido
Se obtiene, con Django en modo "Debug" una página de error con lo siguiente `"TypeError at /admin/voting/voting"`, `"string indices must be integers"`.

### Salida esperada
La salida esperada es la redirección a la misma página de gestión de votaciones del panel de administración de Django (/admin/voting/voting) y los votos recontados al acceder a la página de visualización de la votación (/visualizer/_<int:voting_id>_).

### Sistema operativo
Se está utilizando bajo una máquina virtual con Ubuntu 18.04.1 LTS.

### Versión del software
La versión del producto es la actual, siendo el último commit el a076853776741ba24aa6bd86534528640dbdd9e4.

### Información adicional
Se ha realizado una pequeña investigación en el código para encontrar la causa del error y todo parece indicar que se debe a que no se hace set de la variable "auth-token" en sesión y el sistema no te reconoce como administrador.
Este error no debería afectar solo al recuento de votos (Tally), sino a cualquier método que dependa del "token" nombrado anteriormente.

**Comment by carmenJaraAlvarez** [comment]
Reproducido el bug.

**Comment by carmenJaraAlvarez** [comment]
Trás solucionar el bug #34, este sigue produciéndose.
Debuguendado se detecta que el método new_authenticate no se está utilizando, ya que la aplicación recurre al authenticate default. 
Se renombra y se reestructura, porque la información que proviene del formulario de login del administrador viene con label "username".
El método funciona, sin la creación de token para inclusión en sessión.
Actualmente el token se raliza con post a authenticate/login. No identifica fallo, simplemente no contesta.

**Comment by carmenJaraAlvarez** [comment]
Se ha realizado el token desde el propio método authenticate. 
Con ello, la aplicación funciona siempre que admin y votante no compartan el navegador o el administrador se desloguee y loguee de nuevo.

**Comment by javirogo** [comment]
Tras una reunión entre los miembros del equipo, donde se ha investigado más acerca del fallo explicado en la Issue #35, se ha concretado el fallo producido y cómo solucionarlo.

Para comenzar, se han realizado cambios en el método authenticate (del backend.py) para que funcione correctamente.
- Se ha cambiado el nombre de la función "new_authenticate" por "authenticate", y de esta manera se utiliza esta función a la hora de iniciar sesión.
- Además se ha cambiado la funcionalidad, corrigiendo errores que provocaban una segunda autenticación dentro de la página que no era posible validar.

El fallo se produce debido a la autenticación de dos o más usuarios a la vez en el mismo navegador.
Si, en vez de realizar todo el proceso de votación desde un mismo navegador, usamos distinto navegador para cada usuario que deba iniciar sesión en el proceso de votación, no se produciría dicho error. Esto se debe a que el token del usuario activo es el del último usuario que haya iniciado sesión en el navegador. Por lo que si comenzamos haciendo una nueva votación con un administrador, y después iniciamos sesión con el usuario que va a votar, su token cambiará. Mientras que si volvemos al panel de administración, el administrador seguirá con la sesión activa pero con el token del usuario anterior. Si en ese momento terminamos la sesión, el token se resetearía. A partir de ahí podríamos volver a iniciar sesión para seguir con el proceso de votación normal.

Es por esto, que como solución a este fallo proponemos lo siguiente:
- Todo el proceso de votación debe poder realizarse fuera del panel de administración de django.
- Además, cualquier usuario debería poder iniciar una nueva votación.

Con las propuestas anteriores, además de solucionar el problema (ya que sólo podría haber una misma sesión activa a la vez en un navegador) se daría una mayor personalización a la aplicación. Permitiendo una navegación más fluida y acorde para el usuario.

Si no se aceptasen dichas propuestas, lo único que habría que considerar sería la manera en la que se crean las votaciones. Dejando siempre un navegador para el administrador de django, y otro para los distintos usuarios que puedan acceder a la votación.

**Comment by carmenJaraAlvarez** [comment]
Se deja en la rama de tarea 'bugs' una solución alternativa con refresco de la sesión, hasta en tanto no se defina la preferencia.
