### ISSUE TITLE
Automatización del despliegue en Heroku

### ISSUE THREAD

**Issue by javirogo** [decide-ganimedes-autenticacion/decide-ganimedes-autenticacion#40]
### Estado actual de la funcionalidad y qué se va a mejorar
Actualmente, no se tiene configurado el despliegue de la aplicación en Heroku, y se pretende implementar dicha funcionalidad.

### Cómo se quiere mejorar y el motivo
Se pretende que el despliegue de la aplicación en Heroku se realice de manera automática, después de que Travis CI realice la build de la rama master del proyecto, comprobando que todo funciona correctamente. Así, cada vez que se suban nuevos cambios de la aplicación a master, se tendrá la aplicación desplegada con dichos cambios, sin necesidad de que algún miembro del equipo lo haga de forma manual. 

### Resultado esperado
Despliegue automático de la aplicación a Heroku, con los últimos cambios de la rama master, tras comprobar Travis CI que la build se realiza correctamente.

### Alternativas consideradas
Se ha considerado realizar el despiegue de Heroku usando Heroku CLI, pero para la automatización hemos creído más conveniente usar la opción de despliegue por GitHub.

### Información adicional
Actualmente, no se dispone de información adicional para esta incidencia.

**Comment by javirogo** [comment]
Para poder subir al repositorio padre toda la configuración de Heroku, pero sin personalizaciones de repositorios hijos se ha decidido actuar de la siguiente manera.

**Proceso para subir la configuración de Heroku:**
- Se añade toda la configuración de Heroku a nuestro repositorio Hijo.
- Se elimina el archivo de _configuración local_ y se añade al archivo .gitignore
- Se sube toda la configuración al padre (de esta manera, en el repositorio padre se encontrará únicamente la configuración común y el .gitignore evitará que se suban las configurraciones locales de los repositorios hijos).
- Se elimina la configuración local del .gitignore y se añade al repositorio hijo.
- Se vuelve a añadir la configuración local al archivo .gitignore para evitar conflictos con el padre.

**¿Por qué es necesario realizar todo este proceso?**
Esto se debe a que un archivo que ya está en el repositorio, aunque se incluya en el archivo .gitignore no se ignorará como debería pasar. Por lo tanto, puesto que en el repositorio padre no es necesaria la configuración local, pero en los hijos sí, el repositorio padre ignorará dicho archivo en cada pull request que reciba, mientras que en los hijos podrá incluirse.

**Comment by PedBerTor** [comment]
Una pregunta sobre la configuración de _Heroku_. Según tengo entendido, el repositorio que yo configure en _Heroku_ es el que se va a subir a despliegue cuando yo haga _push_. ¿Puedo configurar una rama concreta del repositorio? Por ejemplo, en mi caso subimos todo a _master_, pero las versiones estables están en _releases_.

**Comment by javirogo** [comment]
Por supuesto, en la sección de despliegue (dentro de la web de Heroku) podéis seleccionar la rama desde la que queréis que se despliegue al producirse un "push".

![image](https://user-images.githubusercontent.com/14946011/50691936-94100d80-1032-11e9-81fa-a01c4e2241fc.png)

En nuestro caso seleccionamos master, pero podríais seleccionar la rama que más os convenga.
En el archivo de configuración local de Heroku sólo se especifica la URL donde se va a desplegar, por lo que no restringe la rama en la que se hará dicho despliegue.

**Comment by PedBerTor** [comment]
Muchas gracias @javirogo, ya hemos configurado correctamente _Heroku_ desde cabina.

**Comment by javirogo** [comment]
Puesto que actualmente ya está funcionando correctamente el despliegue, y se han realizado diversos cambios con respecto al planteamiento inicial que se tomó. Procedo a explicar la solución tomada y a cerrar la incidencia.

## Cómo configurar Heroku en nuestro repositorio
### Paso 1: Crear una aplicación en Heroku
Para crear una aplicación en Heroku deberemos registrarnos previamente.
Una vez en el menú principal de Heroku, podremos seleccionar la opción "new" -> "create new app"
![image](https://user-images.githubusercontent.com/14946011/50692501-6b891300-1034-11e9-83ba-8479256115fe.png)
Sólo debéis rellenar el nombre (comprobando que esté disponible) y seleccionar Europa como región. No es necesario crear un pipeline en este caso, ya que nuestro despliegue es básico.
![image](https://user-images.githubusercontent.com/14946011/50692566-a5f2b000-1034-11e9-9a66-85a695bc60b6.png)

### Paso 2: Configurar el despliegue
Hay diversas formas de realizar el despliegue, por ejemplo, a través de travis o directamente enlazando github con Heroku. En nuestro caso utilizaremos la segunda forma.

Para ello, en la pestaña de deploy (dentro de la nueva aplicación que hemos creado) seleccionaremos GitHub como método de despliegue.
![image](https://user-images.githubusercontent.com/14946011/50692748-27e2d900-1035-11e9-9edc-111ec20a057f.png)

Automáticamente, debajo nos permitirá buscar los repositorios que tenemos para enlazar a la aplicación de Heroku. No obstante, en nuestro caso se trata de una organización, por lo que deberemos dar permisos para acceder a ella. Para ello pulsaremos en donde dice "Ensure Heroku Dashboard has team access."
![image](https://user-images.githubusercontent.com/14946011/50692806-5d87c200-1035-11e9-8f09-9dba18d52ef2.png)

En esa página nos saldrán todas las organizaciones a las que pertenezcas, y los permisos que tiene Heroku sobre ellas. Cabe destacar que si no eres administrador de la aplicación sólo podrás hacer una petición de permisos ("request"), pero si eres administrador entonces podrás garantizarlos directamente ("grant")
![image](https://user-images.githubusercontent.com/14946011/50692924-c40ce000-1035-11e9-98b8-88c06eb4ed95.png)
En este caso, ya hay dos organizaciones con permisos, otras dos en las que no tendríamos permisos de administrador, y una última (creada para esta explicación) en la que podríamos garantizar los permisos.

Una vez tengamos los permisos en Heroku, volveremos a la pestaña de despliegue, donde ya podremos seleccionar la organización y el respositorio sobre el que queremos realizar el despliegue.
![image](https://user-images.githubusercontent.com/14946011/50693050-2239c300-1036-11e9-8b92-08a10b116044.png)

Para poder automatizar el despliegue podremos elegir en esta misma sección sobre qué rama queremos realizarlo e incluso (en el caso de que estemos utilizando Travis CI para la integración contínua) pedirle que sólo realice el despliegue si se ha pasado correctamente Travis.
En nuestro caso forzaremos esa opción, ya que disponemos de integración continua.
![image](https://user-images.githubusercontent.com/14946011/50693309-ddfaf280-1036-11e9-8582-33eb606bddb4.png)

### Paso 3: Crear variables de entorno
Estas variables son opcionales y dependen de la metodología de trabajo que se esté usando.
En nuestro caso tenemos una organización padre (con su repositorio) y varios repositorios que extienden del padre los cuales se alojan o no en distintas organizaciones. Es por esto, que con tanta variedad entre equipos hemos tenido que recurrir a la creación de algunas variables para personalizar mediante ellas todo el proceso.

Para crear una variable debemos ir a la pestaña "settings" dentro de nuestra aplicación de Heroku.
![image](https://user-images.githubusercontent.com/14946011/50693556-9a54b880-1037-11e9-8fb5-b5d2f4c1a79b.png)

Las variables que hemos creado son dos:
- HEROKU: Esta variable la usaremos en el archivo "settings.py" del proyecto para especificar que queremos una configuración concreta si se está desplegando en Heroku (se ha creado algo similar tanto con travis como con la configuración local de nuestra máquina).
- REPO_NAME: Esta variable contendrá únicamente el nombre de la aplicación de Heroku. Esto se ha realizado para que, al tener compartido el mismo archivo local en todos los repositorios, cada uno pueda desplegarse con una aplicación distinta.

En la siguiente imagen mostramos la configuración realizada en el archivo "settings.py", en la cuál se pueden apreciar las dos variables.
![image](https://user-images.githubusercontent.com/14946011/50693762-3979b000-1038-11e9-8d13-23d3b6bd5140.png)

En concreto, la segunda variable se utiliza del modo anteriormente explicado debido a que Heroku siempre se despliega con una URL concreta formada por el patrón que se muestra en esa imagen. Aun así, podéis consultar la ruta de despliegue de vuestra aplicación en la pestaña "settings" de la aplicación de Heroku. En nuestro caso sería la siguiente:
![image](https://user-images.githubusercontent.com/14946011/50693931-c6246e00-1038-11e9-8c07-65f550f76b3d.png)
Donde se puede observar que la parte subrayada es el nombre que pusimos a la aplicación de Heroku.

Y por lo tanto nuestras variables quedarían tal que así:
![image](https://user-images.githubusercontent.com/14946011/50693984-ed7b3b00-1038-11e9-9bc8-0177f319975f.png)

### Paso 4: Crear los archivos de configuración en nuestro repositorio de GitHub
Para nuestra configuración, tal como hemos ido explicando aquí, necesitaríamos crear tres archivos nuevos ("Procfile", "runtime.txt" y local_settings_heroku.py") y modificar dos ("requirements.txt" y "settings.py").
**Nota: tener cuidado con las mayúsculas y las minúsculas en el nombre del archivo, ya que si no coinciden no funcionará.**

##### Procfile
Se encarga de ejecutar ciertos comandos que permitan la ejecución posterior de la aplicación a la hora de desplegar. En nuestro caso hemos añadido la opción makemigrations, ya que la base de datos puede cambiar cada cierto tiempo, y eso hace que se actualicen los archivos que la van a generar.

![image](https://user-images.githubusercontent.com/14946011/50694288-c8d39300-1039-11e9-90b3-44199dfed1d1.png)

Aunque en la imagen no aparece, se deberá añadir también la orden "compilemessages" para que se creen las traducciones.

##### runtime.txt
En este caso sólo especificaremos la versión de python que se usará.

![image](https://user-images.githubusercontent.com/14946011/50694529-65963080-103a-11e9-98b4-dce182811b48.png)

##### local_settings_heroku.py
En este archivo incluiremos la configuración local personalizada para Heroku.

![image](https://user-images.githubusercontent.com/14946011/50694617-abeb8f80-103a-11e9-89cd-63ea6d9e53ae.png)

Lo más importante en este caso es la inclusión de la línea: "APIS = {}"

##### requirements.txt
Tan sólo deberemos añadir las dos líneas siguientes:

![image](https://user-images.githubusercontent.com/14946011/50694717-ed7c3a80-103a-11e9-9639-08ea87d4beff.png)

##### settings.py
Tal y como mostramos en el paso 3.

![image](https://user-images.githubusercontent.com/14946011/50694799-261c1400-103b-11e9-89d4-6ccd0ec8c813.png)

### Paso 5: Comprobar que todo funciona
Para la comprobación final, tendremos que realizar un push a la rama que hayamos seleccionado en el paso 2. En nuestro caso es a la rama master.
Una vez realizado el push esperaremos a que pase travis (si tenemos marcada la casilla de integración contínua). En el caso de que no estuviese marcada el despliegue comenzará al momento.
Para visualizarlo podremos ir a nuestra aplicación de Heroku, y en la página principal nos aparecerá un mensaje avisando que se está desplegando donde podremos ver el log.
Una vez haya terminado el primer despliegue podremos ver como se ha generado la base de datos y se ha desplegado correctamente:

![image](https://user-images.githubusercontent.com/14946011/50695103-020d0280-103c-11e9-9ab1-003d890fc21c.png)

Y para finalizar, debemos saber que existe una opción desde GitHub que nos permite ver dicho despliegue automáticamente. Para ello debemos ir a nuestro repositorio, y aparecerá la opción "enviroments":
![image](https://user-images.githubusercontent.com/14946011/50695250-79db2d00-103c-11e9-8ada-a0a4cea95755.png)

Si accedemos a ella podremos ver todos los sistemas que estamos utilizando para desplegar nuestra aplicación de GitHub (que tengamos enlazadas, claro).
![image](https://user-images.githubusercontent.com/14946011/50695394-cfafd500-103c-11e9-935e-aaefa268cc04.png)

Si pulsamos en "View deployment" podremos ver nuestra aplicación funcionando.

**Comment by javirogo** [comment]
Se ha detectado un nuevo problema.
Ocurre al tratar de crear un superusuario desde la consola.
Se está trabajando para solucionarlo.

![image](https://user-images.githubusercontent.com/14946011/50708203-cb4ae280-1063-11e9-9b6a-d78a9ace53af.png)

**Comment by javirogo** [comment]
Tras haber realizado diversas pruebas. Hemos comprobado que es necesario subir los archivos generados por las migraciones para que Heroku tenga un correcto funcionamiento tras su despliegue.

Es por esto que se va a modificar el archivo ".gitignore" para que dichos archivos dejen de ser ignorados.
Además, con este cambio ya no será necesario la orden "makemigrations", dentro del archivo Procfile.

Por todo esto, se editará el comentario de explicación que se ha expuesto en esta misma incidencia para prevenir ciertos errores.

Dejo la incidencia abierta hasta que se suban todos los archivos al repositorio padre, por si surgiese algún otro problema.

Saludos.

**Comment by javirogo** [comment]
Tras investigar más a fondo, hemos logrado crear un superusuario por defecto a través de comando desde el archivo "Procfile"
Por esta razón, se eliminan las migraciones del repositorio, además de para evitar conflictos.
El usuario creado por defecto será:
- User: admin@decide.com
- Password: practica

Si se decidiese crear un nuevo superusuario sería necesario ejecutar los siguientes comandos:
$ heroku run -a decide-ganimedes bash
$ ./decide/manage makemigrations
$ ./decide/manage migrate
$ ./decide/manage createsuperuser

donde "decide-ganimedes" será el nombre de la aplicación de Heroku en la que se pretenda crear dicho superusuario.

Se ha actualizado el [comentario ](https://github.com/decide-ganimedes-autenticacion/decide-ganimedes-autenticacion/issues/40#issuecomment-451473649)con toda la nueva información.

**Comment by javirogo** [comment]
**Actualización**
Se ha corregido un problema relacionado con el despliegue de Heroku.
Toda la información se puede consultar en la Issue decide-ganimedes-autenticacion/decide-ganimedes-autenticacion#88.

Una vez subidos los últimos cambios al padre, se cerrará esta incidencia.

**Comment by javirogo** [comment]
Actualizado el [mensaje ](https://github.com/decide-ganimedes-autenticacion/decide-ganimedes-autenticacion/issues/40#issuecomment-451473649)con la compilación de las traducciones.

Puesto que todo esto ya se ha subido al repositorio padre, y está funcionando correctamente, procedemos a cerrar la incidencia.
