### ISSUE TITLE
Automatización de Release con Travis

### ISSUE THREAD

**Issue by javirogo** [decide-ganimedes-autenticacion/decide-ganimedes-autenticacion#59]
Se pretende automatizar la creación de nuevas Release a través de Travis siempre que actualice la rama Master de nuestro proyecto.

Para ello será necesario modificar el fichero .travis.yml

El versionado se ha propuesto que deberá ser nombrado de la siguiente manera:
- vX.Y.ZZZ

Donde:
- X corresponderá al milestone actual. Por ejemplo, si nos encontramos en el Milstone 1 será "1".
- Y se podrá ir agregando según estimemos por cada funcionalidad o Issue que completemos.
- Z se corresponderá al "BUILD_NUMBER" de travis, el cual se aumentará de manera automática.
Tanto X como Y deberemos definirlos a mano en el script e incrementarlos cuando consideremos oportunos.

**Comment by davigldom** [comment]
En mi opinión deberíamos mantener el formato de releases proveniente de la primera release creada por Wadobo, el cual tiene el año al final de la release. Por ejemplo: v1.0.0-2018

**Comment by carmenJaraAlvarez** [comment]
Estimo, que dado el breve espacio de tiempo que queda de proyecto, debemos simplificar la nomenclatura. Evitando la numeración intermedia Y. Tenemos que tener en cuenta que de forma habitual, para la integración con los otros subsistemas, se sube al repositorio padre issues sin finalizar en la mayoría de las ocasiones
Incluso cuando se sube una issue finalizada, suele acompañarse de otras a medias.

**Comment by davigldom** [comment]
Por otro lado, la "Z" debería ser el número de releases pertenecientes al milestone actual, en vez de directamente el "BUILD_NUMBER" de Travis CI, ya que se ha implementado las releases cuando ya estamos en la build número 106.

**Comment by javirogo** [comment]
> Estimo, que dado el breve espacio de tiempo que queda de proyecto, debemos simplificar la nomenclatura. Evitando la numeración intermedia Y. Tenemos que tener en cuenta que de forma habitual, para la integración con los otros subsistemas, se sube al repositorio padre issues sin finalizar en la mayoría de las ocasiones
> Incluso cuando se sube una issue finalizada, suele acompañarse de otras a medias.

Para mantener el formato de la primera release creada por Wadobo, tal como dice David, será mejor mantener el formato a pesar del breve espacio de tiempo que queda de proyecto.
Es por esto que finalmente mantendremos la misma nomenclatura cambiando el "BUILD_NUMBER" y añadiendo detrás el año precedido por un guión.
Ejemplo: __v3.0.1-2018__ sería el versionado de la segunda release creada en el milestone 3 en 2018.

**Comment by davigldom** [comment]
Se ha estado implementando la automatización en un [fork aparte](https://github.com/davigldom/decide), para no "ensuciar" nuestro repositorio con releases mal hechas.
Se han encontrado múltiples dificultades a la hora de la implementación, en algunos casos, debido a la falta de documentación de dichas dificultades. A continuación, se enumeran todas las dificultades, la solución a ellas, y una explicación:
- La principal dificultad era el fallo de autenticación usando un "Personal access token" de GitHub como "api-key" en el apartado "deploy" del script de Travis CI. Este token, por motivos de seguridad, solo podía ser usado una vez en público (posteriormente se borraba y pasaba a ser inútil), por lo que una vez usado al hacer commit de su inclusión en el fichero ".travis.yml", ya no podía ser usado para el "deploy" de Travis CI, devolviendo un error de "Bad credentials". Como solución, dicho token debía ser utilizado por primera vez en público para encriptarlo por consola usando el comando "travis encrypt <token> --add deploy.api-key" (el cual también añade dicho token encriptado al "api-key" en el fichero .travis.yml"). Una vez encriptado, el token puede ser utilizado siempre, señalando que está encriptado mediante "secure", solucionando así dicho problema:

        api-key:
          secure: <token_encriptado>

  Cabe destacar que para esta implementación se ha utilizado un "Personal access token" propio de mi 
  cuenta de GitHub "davigldom", ya que no existe un token para las organizaciones.
- Otra dificultad era la necesidad de automatizar las tags, y no tener que añadirlas a mano. Para ello, el primer paso es en el apartado "deploy", poner "tags" en false. Luego, hay que señalar en "before_deploy" como va a ser la tag. Esto se consigue mediante el comando "git tag -a $GIT_TAG", habiendo guardado con anterioridad el formato de la tag en la variable $GIT_TAG. En nuestro caso, nuestro $GIT_TAG depende del $TRAVIS_BUILD_NUMBER y del año actual, siendo el resto de números modificables manualmente.
- Por último, es necesario que la releases automáticas solo se realicen cuando se haga un push de master, ya que Travis CI también realiza la build (en nuestro caso) cuando se hace push de develop. Para ello, el primer paso es hacer que el archivo .zip del proyecto solo se genere cuando Travis CI esté realizando la build de master, ya que en el comando hay que señalar qué rama se va a exportar en el fichero. Esto se consigue añadiendo un if antes del comando, resultando: "if [[ $TRAVIS_BRANCH == "master" ]]; then git archive --format zip --output ./decide.zip master; fi". Por otro lado, para que el deploy (y, por tanto, el release) solo se realice en la rama master, hay que añadir "on: branch: master" al apartado "deploy" del fichero ".travis.yml". Cabe destacar que al señalar esto en el apartado "deploy", el apartado "before_deploy" tampoco se ejecutará si no se ejecuta éste. Respecto a los pull request, las releases, por defecto, no se realizan cuando Travis CI compila por un pull request.

Procedo a transferir toda la automatización desde el [otro fork](https://github.com/davigldom/decide) a una nueva rama, comprobar que todo funciona correctamente y subir estos cambios a nuestra rama master con los mecanismos correspondientes, además de realizar posteriormente la release v2.0.0-2018 correspondiente al Milestone 2.

**Comment by davigldom** [comment]
> Se ha estado implementando la automatización en un [fork aparte](https://github.com/davigldom/decide), para no "ensuciar" nuestro repositorio con releases mal hechas.
> Se han encontrado múltiples dificultades a la hora de la implementación, en algunos casos, debido a la falta de documentación de dichas dificultades. A continuación, se enumeran todas las dificultades, la solución a ellas, y una explicación:
> 
> * La principal dificultad era el fallo de autenticación usando un "Personal access token" de GitHub como "api-key" en el apartado "deploy" del script de Travis CI. Este token, por motivos de seguridad, solo podía ser usado una vez en público (posteriormente se borraba y pasaba a ser inútil), por lo que una vez usado al hacer commit de su inclusión en el fichero ".travis.yml", ya no podía ser usado para el "deploy" de Travis CI, devolviendo un error de "Bad credentials". Como solución, dicho token debía ser utilizado por primera vez en público para encriptarlo por consola usando el comando "travis encrypt  --add deploy.api-key" (el cual también añade dicho token encriptado al "api-key" en el fichero .travis.yml"). Una vez encriptado, el token puede ser utilizado siempre, señalando que está encriptado mediante "secure", solucionando así dicho problema:
>   ```
>     api-key:
>       secure: <token_encriptado>
>   ```
>   Cabe destacar que para esta implementación se ha utilizado un "Personal access token" propio de mi
>   cuenta de GitHub "davigldom", ya que no existe un token para las organizaciones.
> * Otra dificultad era la necesidad de automatizar las tags, y no tener que añadirlas a mano. Para ello, el primer paso es en el apartado "deploy", poner "tags" en false. Luego, hay que señalar en "before_deploy" como va a ser la tag. Esto se consigue mediante el comando "git tag -a $GIT_TAG", habiendo guardado con anterioridad el formato de la tag en la variable $GIT_TAG. En nuestro caso, nuestro $GIT_TAG depende del $TRAVIS_BUILD_NUMBER y del año actual, siendo el resto de números modificables manualmente.
> * Por último, es necesario que la releases automáticas solo se realicen cuando se haga un push de master, ya que Travis CI también realiza la build (en nuestro caso) cuando se hace push de develop. Para ello, el primer paso es hacer que el archivo .zip del proyecto solo se genere cuando Travis CI esté realizando la build de master, ya que en el comando hay que señalar qué rama se va a exportar en el fichero. Esto se consigue añadiendo un if antes del comando, resultando: "if [[ $TRAVIS_BRANCH == "master" ]]; then git archive --format zip --output ./decide.zip master; fi". Por otro lado, para que el deploy (y, por tanto, el release) solo se realice en la rama master, hay que añadir "on: branch: master" al apartado "deploy" del fichero ".travis.yml". Cabe destacar que al señalar esto en el apartado "deploy", el apartado "before_deploy" tampoco se ejecutará si no se ejecuta éste. Respecto a los pull request, las releases, por defecto, no se realizan cuando Travis CI compila por un pull request.
> 
> Procedo a transferir toda la automatización desde el [otro fork](https://github.com/davigldom/decide) a una nueva rama, comprobar que todo funciona correctamente y subir estos cambios a nuestra rama master con los mecanismos correspondientes, además de realizar posteriormente la release v2.0.0-2018 correspondiente al Milestone 2.

En el commit correspondiente se añadirá una explicación de todo esto, aunque más escueta.

**Comment by javirogo** [comment]
Puesto que el "BUILD_NUMBER" puede ser incrementado varias veces antes de realizarse una release (por ejemplo, al realizar varias actualizaciones en la rama "develop"), se ha optado por utilizar directamente la variable "BUILD_NUMBER" de travis sin modificarla para que comience con un número bajo, ya que de esta manera nos referenciará específicamente el número de despliegue que se utilizó en travís para dicha release.

**Comment by davigldom** [comment]
Se acaba de comprobar, antes de pasar la implementación a este repositorio, que todo funciona correctamente aunque el owner del repositorio sea una organización, en vez del propietario del "Personal access token", siempre y cuando el dicho propietario también sea owner de la organización.

**Comment by davigldom** [comment]
Todos los cambios ya están en la rama develop, a la espera de aceptar el pull request actual. No se ha realizado la release, como era de esperar, ya que el push ha sido de la rama develop, además de detectar que hay una pull request abierta.

Por otro lado, en las pruebas en el otro fork, al hacer las releases después de aceptar un pull request, el mensaje de merge de dicho pull request se añadía a la release. No se sabe todavía el porqué, ni cómo eliminarlo.

**Comment by davigldom** [comment]
> Es necesario utilizar un nuevo token para este repositorio.

Al parecer no se puede utilizar el mismo "Personal access token" en dos repositorios distintos. Ya he creado uno nuevo, lo he añadido al script y procedo a subir los cambios y hacer un nuevo pull request, necesario para que se realice la release automática.

**Comment by davigldom** [comment]
> Todos los cambios ya están en la rama develop, a la espera de aceptar el pull request actual. No se ha realizado la release, como era de esperar, ya que el push ha sido de la rama develop, además de detectar que hay una pull request abierta.
> 
> Por otro lado, en las pruebas en el [otro fork](https://github.com/davigldom/decide), al hacer las releases después de aceptar un pull request, el mensaje de merge de dicho pull request se añadía a la [release](https://github.com/davigldom/decide/releases/tag/v1.0.114-2018). No se sabe todavía el porqué, ni cómo eliminarlo.

Se ha realizado la release correctamente con el cambio del token. Cabe destacar que, como se indica en el comentario referenciado, a la release se le añade el mensaje del merge automáticamente, no sabemos porqué ni como eliminarlo.

**Comment by davigldom** [comment]
Después de haber dejado pasar un tiempo para comprobar que no se reportan errores en la automatización de las releases de GitHub con Travis CI, además de que otros módulos han usado esta configuración para hacer sus releases y les funciona correctamente; se va a dejar constancia en este comentario el procedimiento para configurarlo todo correctamente. Este comentario será pasado posteriormente al documento del proyecto, y replicado al repositorio padre de Decide-Ganímedes, si lo requieren. Cabe destacar que el procedimiento parte de tener Travis CI configurado correctamente para realizar la build del proyecto y funcionando a la perfección.

## Configuración de releases automáticas de GitHub con Travis CI
### Paso 1: Cambiar el script ".travis.yml"
Lo primero que necesitaremos es realizar una serie de cambios en el script ".travis.yml" para que Travis CI realice la release en GitHub después de pasar los tests correspondientes. Para ello partiremos del script siguiente:
![image](https://user-images.githubusercontent.com/34518143/50725854-dc97fb80-1104-11e9-9cc8-9f46071b3f9a.png)

#### Paso 1.1: Cambiar el apartado "script"
El primer cambio en dicho script será la inclusión de un comando de git para exportar a un archivo .zip el código del proyecto. Dicho archivo será necesario para realizar la release más adelante. Cabe destacar, que el archivo se creará en el flujo de trabajo de Travis CI, por lo que se borrara del directorio una vez Travis CI termine, al igual que la base de datos que utilice. Este comando para crear el .zip habrá que escribirlo en el apartado "script" dentro de .travis.yml, quedando de la siguiente manera:
![image](https://user-images.githubusercontent.com/34518143/50725905-ad35be80-1105-11e9-8219-68ef32f863ed.png)

Podemos observar que al comando en cuestión, `git archive --format zip --output ./decide.zip master` hay que pasarle tres variables: el formato del archivo (en nuestro caso será zip), el nombre del archivo a generar (en nuestro caso es decide.zip y se creará en el directorio actual), y la rama de la cual se exportará el codigo (en nuestro caso será master).

Por otro lado, este comando se encuentra dentro de una condición if. La primera parte de dicha condición (`$TRAVIS_BRANCH == master`) comprueba que Travis CI esté realizando la build en la rama master para exportar el .zip. Esto está configurado de esta manera, ya que nosotros queremos que las releases se hagan desde la rama master (observemos que al .zip le exportamos el código de la misma rama que pongamos en esta condición, sino el comando devolverá error), pero la rama puede ser cualquiera. La segunda parte de la condición (`$DEPLOY_TRAVIS == "1"`), comprueba que una variable de entorno, creada en la web de Travis, llamada "DEPLOY_TRAVIS" tenga su valor en 1. Esta comprobación se usa para que, cuando no queramos realizar releases en la rama especificada por cualquier razón, cambiaremos su valor a 0 (ya veremos más adelante como se configuran las variables de entorno en la web de Travis).

Despúes del comando, se encuentra un "echo" de un mensaje, utilizado para comprobar en el log de una build de Travis CI si el .zip se ha creado o no, ya que siempre devuelve un 0, entre dentro del if o no:
![image](https://user-images.githubusercontent.com/34518143/50726039-a3ad5600-1107-11e9-9f53-bcbf62943e5a.png)
Caso en el que no ha entrado dentro del if (push a la rama develop)

![image](https://user-images.githubusercontent.com/34518143/50726061-e111e380-1107-11e9-9a56-afff62a07ee0.png)
Caso en el que sí ha entrado dentro del if (push a master)

#### Paso 1.2: Añadir el apartado "before_deploy"
El segundo cambio será la inclusión de un apartado "before_deploy", el cual utilizaremos para crear la tag correspondiente a la release que se va a generar. Para ello, escribiremos el siguiente código:
![image](https://user-images.githubusercontent.com/34518143/50726091-6e553800-1108-11e9-9dc2-7a91b6b2e6ca.png)

Los dos primeros comandos de la imagen se usaran para indicar a GitHub nuestro nombre y email para subir la tag, igual que tenemos que configurarlo cuando nos bajamos el repositorio a nuestra máquina. En mi caso, he puesto mi nombre de usuario de GitHub y el email asociado, ustedes tendrán que poner los suyos, como es lógico.

El tercer comando, crea una variable llamada "YEAR" con el año actual, la cual se usa para introducir el año en la tag de la release. Este comando es algo opcional nuestro, ya que queremos que nuestras tags sean de la forma v2.0.0-2019.

El cuarto comando, guarda en una variable la tag que queremos añadir a la release. En nuestro caso, dicha tag será de la forma v2.0.0-2019, donde el primer número vendrá de una variable de entorno llamada "MILESTONE_TRAVIS" (más adelante explicaremos como se crean), el siguiente número es un 0, el siguiente proviene de una variable de entorno por defecto de Travis, la cual es el número de la build actual ("TRAVIS_BUILD_NUMBER), y finaliza con el año, obtenido de la variable creada en el comando anterior. Se pueden consultar todas las variables de entorno por defecto que tiene Travis en el siguiente enlace: https://docs.travis-ci.com/user/environment-variables/. Estas variables nos pueden servir de ayuda para construir una tag personalizada, según los parámetros que queramos incluir en ella.

Por último, hay que añadir dicha tag a GitHub. Al último comando se le pasa la variable con la tag creada anteriormente, y se le añade un mensaje (esto es opcional).

#### Paso 1.3: Añadir el apartado "deploy"
El último cambio en ".travis.yml" será la inclusión del apartado "deploy", el cual será el encargado de crear la release. El código de dicho apartado es el siguiente:
![image](https://user-images.githubusercontent.com/34518143/50726195-d6584e00-1109-11e9-9d11-79f596863335.png)

En este apartado, lo primero que hay que hacer es indicar que dicho deploy es para hacer una release. Para esto es `provider: releases`.

Después, tenemos que introducir un token de GitHub, el cual usará Travis CI para autenticarse en nuestro repositorio, y poder añadir la release. Este token, deberá ir encriptado, ya que sino GitHub tiene mecanismos de protección que solo permite usar el token públicamente como tal una vez. Por ello, tras `api-key:` debemos indicar que el token va encriptado con `secure`. Explicaremos cómo crear este token en el siguiente paso.

Luego, debemos indicar el archivo con el código del proyecto. Aquí deberemos escribir el nombre del fichero .zip que hemos generado en el apartado "script".

Para eliminar todos los cambios realizados en el repositorio durante el deploy, usamos `skip_cleanup: true`.

Por último, tenemos que incluir una serie de condiciones en el `on:`:
- La rama en la que queremos realizar la release, en nuestro caso, será en la rama master (`branch: master`).
- Usaremos la variable usada al exportar el .zip, "DEPLOY_TRAVIS", para que solo se realice la release si ésta tiene valor 1, para así evitar que se hagan releases si no queremos (`condition: $DEPLOY_TRAVIS = 1`).
- Para que Travis CI no nos pregunte por la tag que queremos añadir, y así utilice la creada en el apartado "before_deploy"), pondremos `tags: false`.
Cabe destacar, que estas condiciones también afectan a los comandos del apartado "before_deploy", es decir, Travis CI no realizará dichos comandos si está realizando al build en una rama diferente a la que hemos especificado (master en nuestro caso), o si la variable "DEPLOY_TRAVIS" está a 0. Es por esta razón, que no hemos comprobado estas dos condiciones con un if en el apartado "before_deploy", como sí hicimos en el apartado "script" para el comando que exportaba al .zip.

Otro aspecto importante a recalcar es que, por defecto, los releases no se realizarán al crear un pull request a la rama especificada, solo se creará cuando dicho pull request es aceptado y realizado el "merge".

### Paso 2: Creación del "Personal access token"
Debido a que las organizaciones no tienen un "Personal access token" deberemos crear uno desde la cuenta de GitHub de algunos de los propietarios de dicha organización. Para ello, nos vamos al apartado "Settings" de nuestro perfil, luego a "Developer settings", y ahí entramos en "Personal access tokens". Para crear un nuevo token, pulsamos en el botón de "Generate new token", y nos llevará a una vista como la siguiente:
![image](https://user-images.githubusercontent.com/34518143/50726388-a65e7a00-110c-11e9-9fec-b064202fcf09.png)

En ella, escribimos una descripción del token en el apartado "Token description", seleccionamos todos los permisos de "repo" en el apartado "Select scopes", y le damos a "Generate token". Esto nos devolverá a la vista anterior, y habrá aparecido el número del nuevo token creado.

El siguiente paso, será encriptarlo con los algoritmos de Travis para poder usarlo en ".travis.yml". Para ello, tendremos que instalar Travis CLI:

     gem install travis

Una vez instalado, ejecutaremos el siguiente comando, al cual hay que añadirle el número del token donde pone "token_git" (quitando las comillas):

     travis encrypt "token_git"

Este comando nos devolverá el token encriptado (un conjunto bastante extenso de número, letras y símbolos), el cual deberemos añadir en el apartado "deploy" de ".travis.yml", concretamente en `api-key: secure:`.

### Paso 3: Configuración de las variables de entorno en la web de Travis
Para configurar las variables de entorno que hemos ido nombrando a lo largo del tutorial, deberemos entrar en la web de Travis, acceder al repositorio de nuestro proyecto, y entrar en "Settings". En esta vista, encontraremos un apartado de "Environment Variables":
![image](https://user-images.githubusercontent.com/34518143/50726516-b9724980-110e-11e9-9d0b-73354ce6f461.png)

En dicho apartado, tendremos que ir introduciendo el nombre de la variable de entorno que queramos crear en el apartado "Name", y el valor que tendrá, en el apartado "Value". El selector de "Display value in build log" lo pondremos a true solo cuando queramos que el valor de esa variable se muestre el log de la build de Travis CI. Esto no es recomendable cuando creemos variables con contenido privado, como veremos posteriormente. Además, el valor de la variable no podrá ser visualizado si dicho selector está en false. Cabe destacar que, una vez creada la variable de entorno, no podremos editarla, teniendo que borrarla y crearla de nuevo.

Las variables de entorno que tendremos que crear para que nuestra configuración funcione adecuadamente, según lo visto en este tutorial, son las siguientes:
- **DEPLOY_TRAVIS**: cuyo valor será 1 si queremos que se realice la release, u otro si no queremos que se realice.
- **MILESTONE_TRAVIS**: cuyo valor será el milestone actual del release. Esta variable de entorno es opcional, según como quieras nombrar las tags.

Aparte de estas dos variables de entornos, se pueden crear cualquier otra que ayude a nombrar las tags de las releases.
![image](https://user-images.githubusercontent.com/34518143/50726675-c728ce80-1110-11e9-9e48-6eb2b6dc1f11.png)

---

[EN CONSTRUCCIÓN]
