### ISSUE TITLE
Votación no funciona

### ISSUE THREAD

**Issue by carmenJaraAlvarez** [decide-ganimedes-autenticacion/decide-ganimedes-autenticacion#62]
Incidencia a replicar en repositorio padre

####  Descripción: 

Mensaje de error en votación y excepción en recuento de votos.

#### Pasos para reproducir el problema:

Acceder al formulario de creación de una Voting desde el panel de administración Django (/admin/voting/voting/add)

Añadir pregunta

Añadir usuarios al censo de la votación que se acaba de crear

Iniciar la votación (Start)

Votar con las credenciales de varios de los usuarios censados en la votación

#### ¿Cuál es la salida esperada? 

Mensaje de confirmación de voto enviado que se puede cerrar permaneciendo en la misma página

Sin embargo, tras el cierre del mensaje se obtiene lo siguiente:
![image](https://user-images.githubusercontent.com/44395689/50629916-e07a2100-0f3e-11e9-87df-d31beda38186.png)

#### Sistema operativo/navegador

Se está utilizando bajo una máquina virtual con Ubuntu 18.04.1 LTS

Chromium Version 71.0.3578.98 (Official Build) snap (64-bit)

--------
Tras continuar normalmente, la visualización de los resultados lanza excepción.

**Comment by davigldom** [comment]
Se ha comprobado dichos pasos en el repositorio padre, y sucede los mismos errores. Por tanto, se supone que dichos errores no han sido causados por nuestros cambios, así que se replicara esta incidencia al repositorio padre para que los módulos responsables solucionen los fallos. 
Cabe destacar que el error al visualizar los resultados no era posible comprobarlo, ya que el "tally" no funcionaba hasta que hemos subidos nuestros cambios más recientes. Además, se va a abrir otra incidencia para este fallo.

**Comment by davigldom** [comment]
> Se ha comprobado dichos pasos en el repositorio padre, y sucede los mismos errores. Por tanto, se supone que dichos errores no han sido causados por nuestros cambios, así que se replicará esta incidencia al repositorio padre para que los módulos responsables solucionen los fallos.
> Cabe destacar que el error al visualizar los resultados no era posible comprobarlo, ya que el "tally" no funcionaba hasta que hemos subidos nuestros cambios más recientes. Además, se va a abrir otra incidencia para este fallo.

Se ha detectado que el fallo de esta incidencia se debe a una variable v, a la cual se le asignaba el resultado de una función que se ha eliminado, dejando la variable v suelta.

**Comment by davigldom** [comment]
La incidencia ya ha sido replicada al repositorio padre decide-ganimedes/decide-ganimedes#51

**Comment by davigldom** [comment]
Procedo a cerrar esta incidencia, ya que el coordinador de Cabina tiene solucionado el error, y procederá a subir la solución en futuros pull requests al repositorio padre de Decide-Ganímedes.
