### ISSUE TITLE
Registro e iniciar sesión con redes sociales

### ISSUE THREAD

**Issue by mrchavea** [decide-ganimedes-autenticacion/decide-ganimedes-autenticacion#71]
### Estado actual de la funcionalidad y qué se va a mejorar
Actualmente, el registro de un usuario se realiza a través de un formulario de registro, en el que el usuario tiene que rellenar sus datos manualmente. De igual manera, para autenticarse, un usuario debe introducir su email y su contraseña. Se pretende mejorar estas funcionalidades.

### Cómo se quiere mejorar y el motivo
Para que sea más cómodo y rápido para el usuario, se pretende implementar un registro utilizando la cuenta de una red social que el usuario tenga abierta en ese momento en su navegador, o que se autentique en dicha cuenta, y ésta introduzca los datos del usuario en la base de datos de nuestra aplicación, permitiendo así el registro y autenticarse.

### Resultado esperado
En las vistas de registro y autenticación, debería haber un botón para cada red social que se implemente, permitiendo así registrarse o autenticarse con dicha red social con tan solo pulsar dichos botones.

### Alternativas consideradas
Por ahora se ha considerado implementar como redes sociales Facebook, Twitter, Google y GitHub.

### Información adicional
Sería útil la implementación de una vista la cual permita borrar las redes sociales con las que estés conectado o añadir nuevas.

**Comment by davigldom** [comment]
Una vez que se acepte el pull request actual con los cambios que implementan el registro y autenticación con Google y GitHub, procederé a implementar los de Facebook y Twitter.

**Comment by davigldom** [comment]
Tras hacer varias pruebas durante el día de hoy, se ha podido comprobar que, tras autenticarse con cualquier red social, no es posible votar en nignuna votación, a pesar de ser añadido el usuario al censo de dicha votación. Se ha abierto una incidencia para ello #78.

**Comment by mrchavea** [comment]
Han surgido problemas con la autenticación de Facebook ya que no extraía el email. Solucionado añadiendo en el settings.py:
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
  'locale': 'es_ES',
  'fields': 'id, name, email, age_range'
}

**Comment by mrchavea** [comment]
Ha sido imposible crear el inicio de sesión con Twitter al denegarme la cuenta de desarrollo de Twitter para crear una App,

**Comment by davigldom** [comment]
Se ha detectado un error con GitHub: si no tienes configurado un email público en GitHub e intentas autenticarte con ella, devuelve un error de que el usuario se intenta crear sin el campo "email".

**Comment by mrchavea** [comment]
Tras implementar el inicio de sesión y registro con Github, Facebook y Google se da por finalizada la incidencia al comprobar que los usuarios registrados con redes sociales pueden votar sin errores-
