### ISSUE TITLE
Traducir la interfaz a otros idiomas

### ISSUE THREAD

**Issue by davigldom** [decide-ganimedes-autenticacion/decide-ganimedes-autenticacion#8]
**[Incidencia replicada desde el repositorio padre de Decide-Ganímedes](https://github.com/decide-ganimedes/decide-ganimedes/issues/8)**

### Módulos implicados
Todos, aportando cada módulo un miembro de su equipo a un equipo de internacionalización común.

### Estado actual de la funcionalidad y qué se va a mejorar
La interfaz actual de la aplicación solo se encuentra en español, por lo que se quiere añadir más idiomas.

### Cómo se quiere mejorar y el motivo
Para que la aplicación sea accesible por un mayor número de usuarios, no solo españoles, se pretende añadir traducciones de la interfaz las cuales sean accesibles desde un selector de idioma común en cada vista.

### Resultado esperado
Todas las vistas en todos los idiomas que se acuerden, con un selector para cambiar el idioma en cada vista.

### Alternativas consideradas
Por ahora se han considerado como idiomas a traducir, aparte del español, el inglés y el catalán.

### Información adicional
Supuestamente, se deberá utilizar una librería para facilitar la traducción de toda la interfaz.

**Comment by Rubentoro** [comment]
Con la integración del idioma catalán, es necesario reabrir la Issue. Es necesrio modificar las traducciones y resolver conflictos con los demás módulos, ya que al intentar compilar los mensajes salen duplicados y no se traduce. Se está trabajando también en el selector de idiomas para adaptarlo al CSS

**Comment by Rubentoro** [comment]
Funciona correctamente la traducción de la página completa. Se ha encontrado el problema en el selector en el cual se pide que no se traduzcan los idiomas ofertados. El inglés se traduce de forma automática y no se encuentra la forma de evitarlo.

**Comment by Rubentoro** [comment]
Queda completada la traducción de la aplicación.
![image](https://user-images.githubusercontent.com/28593750/51045909-08175c00-15c5-11e9-87dd-75d6042adb65.png)
![image](https://user-images.githubusercontent.com/28593750/51045935-16657800-15c5-11e9-9523-fdd039677149.png)
![image](https://user-images.githubusercontent.com/28593750/51045968-2715ee00-15c5-11e9-92e2-c201af42203f.png)
![image](https://user-images.githubusercontent.com/28593750/51045987-34cb7380-15c5-11e9-803a-ee39a1b3b273.png)
