### ISSUE TITLE
Error al desplegar la aplicación en docker

### ISSUE THREAD

**Issue by javirogo** [decide-ganimedes-autenticacion/decide-ganimedes-autenticacion#80]
**Incidencia para replicar en el repositorio padre de Decide-Ganímedes**

### Módulos implicados
Ganímedes-censo.

### Descripción del error
Al hacer uso del script generado para realizar el despliegue de docker, se produce un error, el cual nos informa que la base de datos postgreSQL no tiene una versión válida.

### Pasos para reproducir el error
1. Lanzamos el script en una máquina con Ubuntu18
2. Ejecutamos las órdenes en el siguiente orden:
1\) Para comprobar los contenedores de docker y las imágenes generadas anteriormente.
6\) Para eliminar los contenedores de docker.
2\) Para eliminar las imágenes, entre otros componentes de docker.
3\) Para lanzar el despliegue de docker.
3. Una vez finalizado el script, abrir el navegador con la url: http://10.5.0.1:8000
4. La página devolverá un error 502 (Bad request)

### Resultado obtenido
![image](https://user-images.githubusercontent.com/14946011/50784859-34726600-12af-11e9-973a-c500757178cd.png)

![image](https://user-images.githubusercontent.com/14946011/50784561-47386b00-12ae-11e9-9a9f-e36898774905.png)

### Salida esperada
La salida esperada sería la pantalla de bievenida de Ganímedes.

### Sistema operativo
Ubuntu 18

### Versión del software
PostgreSQL 10

### Información adicional
Se ha probado a realizar los comandos de manera manual, y tampoco ha funcionado. Por lo que podemos estimar que el error puede encontrarse dentro de los archivos de configuración de docker.

**Comment by davigldom** [comment]
Incidencia replicada en el repositorio padre de Decide-Ganímedes (decide-ganimedes/decide-ganimedes#63), y asignada al coordinador del módulo de Censo.

**Comment by davigldom** [comment]
**[Comentario replicado desde el repositorio padre de Decide-Ganímedes](https://github.com/decide-ganimedes/decide-ganimedes/issues/63#issuecomment-452028762)**

Respecto a los errores que han salido, no ha sido por el script. En determinadas máquinas Linux (no en todas) aparecen errores en el despliegue debido a que el fichero docker-compose-yml se descarga determinadas versiones que causan conflictos con el resto de contenedores.

Desconozco porque ocurre, ya que a mi me pasó y lo solucioné editando el docker-compose.yml para que descargase una versión concreta y se solucionó, pero por diversos motivos, tuve que formatear mi equipo y al desplegarlo con la configuración del docker-compose.yml por defecto volvió a funcionar. No se si estará relacionado con las dependencias del sistema operativo local. 

Para solucionarlo, tendréis que indicar manualmente en el docker-compose.yml qué versión de imagen tenéis que descargarse para que deje de dar conflicto. Eso se ve fácilmente observando los logs que devuelven los contenedores (Opción del script 7).

En este caso, con se soluciona descargándose la versión de PostgreSQL 11.1

![image](https://user-images.githubusercontent.com/9322398/50785278-69cb8380-12b0-11e9-985c-3d429d1a2a9b.png)

**Comment by carmenJaraAlvarez** [comment]
Se ha aplicado la solución, corrigiéndose el fallo. Despliega correctamente.

**Comment by carmenJaraAlvarez** [comment]
Una vez finalizada la integración con el grupo Ganímedes se realiza nueva prueba, funcionando correctamente.
