### ISSUE TITLE
Unificación de diseño y navegabilidad en la aplicación

### ISSUE THREAD

**Issue by javirogo** [decide-ganimedes-autenticacion/decide-ganimedes-autenticacion#82]
**Incidencia para replicar en el repositorio padre de Decide-Ganímedes**

### Módulos implicados
Todos los módulos se ven implicados, ya que esta incidencia pertenecería (en gran medida) al módulo de Votación, del cuál no disponemos en nuestro grupo de trabajo.

### Estado actual de la funcionalidad y qué se va a mejorar
Actualmente se dispone de una página principal en la que podremos ubicar los enlaces a las distintas secciones de la aplicación.
La sección de autenticación está funcional ahora mismo. Pudiendo incluso iniciar sesión con distintas redes sociales, como Google o GitHub entre otras.

### Cómo se quiere mejorar y el motivo
Se pretende añadir un acceso a los distintos módulos en la sección principal. Para ello se propone añadir como mínimo una lista con todas las votaciones en una vista accesible a cualquier usuario desde la página principal.

### Resultado esperado
Poder acceder a todas las funcionalidades de la aplicación sin necesidad de acceder a la interfaz de administración de django.

### Alternativas consideradas
Hay ciertas funcionalidades que se pueden considerar únicas para el administrador. Gracias al nuevo sistema de autenticación se puede acceder a la interfaz de administración directamente con el usuario que haya iniciado sesión (siempre que disponga de los permisos necesarios). Por lo que, con un botón que nos llevase a la propia interfaz de administración podríamos dar salida a ese tipo de funcionalidades más específicas.

### Información adicional
No hay información adicional.

**Comment by davigldom** [comment]
Replicada al repositorio padre de Decide-Ganimedes (decide-ganimedes/decide-ganimedes#62), y asignada a todos los coordinadores del resto de módulos.

**Comment by mrchavea** [comment]
Se da por finalizada y por consecuencia se cerrará esta incidencia al conseguir el resultado esperado: poder acceder a a todas las funcionalidades de la aplicación sin necesidad de acceder a la interfaz de administración de django sin errores.
