### ISSUE TITLE
Fallo al ejecutar el test de authentication crear un nuevo usuario por recaptcha

### ISSUE THREAD

**Issue by Rubentoro** [decide-ganimedes-autenticacion/decide-ganimedes-autenticacion#87]
### Descripción del error
Al introducir el recaptcha como atributo obligatorio en el registro de nuevo usuario, se ha añadido una propiedad más al formulario llamada 'captcha', la cual no se consigue averiguar su valor en un caso de estar validado. Esto implica que sea imposible introducir esta variable en el test y por tanto que el test pase la ejecución sin fallo.

### Pasos para reproducir el error
_1. Localízate en  ./decide-ganimedes/decide/
_2. Abre un terminal 
_3. Ejecuta los test con el comando ./manage.py test

### Resultado obtenido
![image](https://user-images.githubusercontent.com/28593750/50935728-50bc0180-146d-11e9-9f18-ec05092bf1f4.png)

### Salida esperada
La salida debería ser 0 fallos en los test.

### Sistema operativo
Ubuntu 18.4.1 en máquina virtual

### Información adicional
Se está usando una librería llamada django-nocaptcha-recaptcha, la cual gestiona automáticamente los atributos cuando está importada.

**Comment by davigldom** [comment]
Se ha encontrado la forma de incluir el captcha en el test, y de que no devuelva error. El código importante en el test sería:
```
def test_nuevo_usuario_ok(self):
        os.environ['NORECAPTCHA_TESTING'] = 'True'

        data = {'email': 'new1@mail.com', ..., 'g-recaptcha-response': 'PASSED'}
```
Lo primero de todo es activar el modo de test del paquete utilizado para incluir el captcha, poniendo la variable de entorno "NORECAPTCHA_TESTING" a True. Después, se incluye que el captcha se ha pasado mediante `g-recaptcha-response': 'PASSED'`, dentro de los datos a pasar en el formulario.

Se procede a abrir una nueva rama desde develop, para que se tengan todos los últimos cambios, e implementar en dicha rama el captcha y actualizar el test.
