### ISSUE TITLE
Error en traducciones al realizar el despliegue de Heroku

### ISSUE THREAD

**Issue by Rubentoro** [decide-ganimedes-autenticacion/decide-ganimedes-autenticacion#88]
**Incidencia para replicar en el repositorio padre de Decide-Ganímedes**

### Módulos implicados
Todos los módulos, puesto que el despliegue de Heroku nos compete a todos.

### Descripción del error
Al desplegar Heroku no se realiza la compilación de mensajes, por lo que las traducciones no funcionan correctamente al cambiar de idiomas en la aplicación.

### Pasos para reproducir el error
1. Despliegue su aplicación en Heroku.
2. Acceda a la página principal de la aplicación.
3. Modifique el idioma en el selector de la cabecera.
4. Fíjese que el mensaje de "Welcome" no cambia (ese mensaje debería cambiar al igual que muchos otros, pero cuando ese mensaje concreto funcione, sabremos que el resto también pueden funcionar).

### Resultado obtenido
Las traducciones en la aplicación de Heroku no cambiar. Tan sólo cambian ciertas palabras que pueden traducirse por defecto en django. Por ejemplo: "iniciar sesión", "password", "correo electrónico", ...

### Salida esperada
Se espera que al menos el mensaje de bienvenida cambie su traducción a los siguientes:
- Welcome --> Inglés.
- Bienvenid@ --> Español
- Benvinguda --> Catalán

En el caso de que esta palabra funcione sabremos que la compilación de mensajes se está realizando.

### Sistema operativo
El sistema utilizado por Heroku es el mismo para todos. Está basado en contenedores con Docker en Linux.

### Versión del software
No aplica.

### Información adicional
Sin información adicional

**Comment by javirogo** [comment]
Tras varias horas probando soluciones, desde ganímedes autenticación hemos hallado la solución a este bug que se produce en Heroku.

Dejamos este comentario con todas las pruebas que se han realizado para dejar constancia del trabajo realizado hasta llegar a este punto.
En la última prueba se explicará la solución que se ha tomado y la razón por la cuál ha funcionado, por lo que no es necesario leer todas las anteriores.

### Prueba 1
**Solución probada**

Se añade el comando "python manage.py compilemessages" al archivo "Procfile".

*Procfile*
```
% prepara el repositorio para su despliegue. 
release: sh -c 'cd decide && python manage.py makemigrations && python manage.py migrate && python manage.py compilemessages -&& echo "from django.contrib.auth import get_user_model; User = get_user_model();\nif not User.objects.filter(email='"'"'admin@decide.com'"'"').exists(): User.objects.create_superuser('"'"'admin@decide.com'"'"', '"'"'practica'"'"')" | python3 ./manage.py shell'
% especifica el comando para lanzar Decide
web: sh -c 'cd decide && gunicorn decide.wsgi --log-file -'
```

**Resultado**
[Despliegue fallido](https://dashboard.heroku.com/apps/decide-autenticacion/activity/releases/69a1cc7b-d699-4275-8755-c89466edf306)

![image](https://user-images.githubusercontent.com/14946011/50972163-29ede180-14e6-11e9-8b46-f0c00f29d190.png)

### Prueba 2
**Solución probada**
Se agrega el _buildpack_ gettex a la aplicación de Heroku.
![image](https://user-images.githubusercontent.com/14946011/50972389-d039e700-14e6-11e9-865f-f0a83b11d1c9.png)

**Resultado**
[Depliegue exitoso](https://dashboard.heroku.com/apps/decide-autenticacion/activity/releases/80845252-1af1-41d8-8300-25a075d12eea)
Al final del despliegue nos muestran las líneas de compilación de los mensajes:
![image](https://user-images.githubusercontent.com/14946011/50972469-011a1c00-14e7-11e9-982c-c28cb48ffbde.png)

Pero cuando vamos a comprobar en la aplicación, los mensajes no se traducen.

### Prueba 3
**Solución probada**
Se añade comando para generar los mensajes "python manage.py makemessages -l es && python manage.py makemessages -l ca"

*Procfile*
```
% prepara el repositorio para su despliegue. 
release: sh -c 'cd decide && python manage.py makemigrations && python manage.py migrate && python manage.py makemessages -l es && python manage.py makemessages -l ca && python manage.py compilemessages && echo "from django.contrib.auth import get_user_model; User = get_user_model();\nif not User.objects.filter(email='"'"'admin@decide.com'"'"').exists(): User.objects.create_superuser('"'"'admin@decide.com'"'"', '"'"'practica'"'"')" | python3 ./manage.py shell'
% especifica el comando para lanzar Decide
web: sh -c 'cd decide && gunicorn decide.wsgi --log-file -'
```

**Resultado**
[Despliegue exitoso](https://dashboard.heroku.com/apps/decide-autenticacion/activity/releases/e1f98a37-eca1-4ce3-a65c-fb09332f3eeb)
Al final del despliegue se puede observar de nuevo como se generan los mensajes y se compilan:
![image](https://user-images.githubusercontent.com/14946011/50972669-81408180-14e7-11e9-80b9-ac94ac3e9ab7.png)

Pero las traducciones siguen sin funcionar en la aplicación.

### Prueba 4
**Solución probada**
Probamos con distintos _buildpacks gettext_  (ya que son buildpacks no oficiales).

**Resultado**
Mismos resultados que en la prueba 2. Aparentemente no cambia nada.
Dejamos [esta URL](https://elements.heroku.com/search/buildpacks?q=gettext) con todos los buildpacks encontrados.

### Prueba 5
**Solución probada**
Dejamos uno de los _buidlpacks gettext_ instalados, ya que sin ellos no se pueden compilar los mensajes.
Accedemos a nuestra consola y nos conectamos mediante ella al bash de la aplicación de Heroku.
Desde ahí podemos ejecutar los comandos tal y como lo hacemos en nuestra máquina local.

![image](https://user-images.githubusercontent.com/14946011/50973096-61f62400-14e8-11e9-885b-07130c9af243.png)

**Resultado**
Aunque aparentemente se ejecutan correctamente todos los comandos, los mensajes siguen sin traducirse.

### Prueba 6
**Solución probada**
Se divide el comando "python manage.py compilemessages" en dos subcomandos que compilen los mensajes por separado de cada idioma.

*Procfile*
```
% prepara el repositorio para su despliegue. 
release: sh -c 'cd decide && python manage.py makemigrations && python manage.py migrate &&  python manage.py makemessages -l es && python manage.py makemessages -l ca && python manage.py compilemessages -l es && python manage.py compilemessages -l ca && echo "from django.contrib.auth import get_user_model; User = get_user_model();\nif not User.objects.filter(email='"'"'admin@decide.com'"'"').exists(): User.objects.create_superuser('"'"'admin@decide.com'"'"', '"'"'practica'"'"')" | python3 ./manage.py shell'
% especifica el comando para lanzar Decide
web: sh -c 'cd decide && gunicorn decide.wsgi --log-file -'
```

**Resultado**
[Despliegue exitoso](https://dashboard.heroku.com/apps/decide-autenticacion/activity/releases/d688b9e6-6bb5-4bd8-98e5-c7aa3bfbb483)
Pese al despliegue. La página sigue sin traducirse.

### Prueba 7 [Solución]
**Solución probada**
Se eliminan los comandos makemessages y compilemessages de la línea "release" y se añaden a la línea "web".

*Procfile*
```
% prepara el repositorio para su despliegue. 
release: sh -c 'cd decide && python manage.py makemigrations && python manage.py migrate && echo "from django.contrib.auth import get_user_model; User = get_user_model();\nif not User.objects.filter(email='"'"'admin@decide.com'"'"').exists(): User.objects.create_superuser('"'"'admin@decide.com'"'"', '"'"'practica'"'"')" | python3 ./manage.py shell'
% especifica el comando para lanzar Decide
web: sh -c 'cd decide &&  python manage.py makemessages -l es && python manage.py makemessages -l ca && python manage.py compilemessages -l es && python manage.py compilemessages -l ca && gunicorn decide.wsgi --log-file -'
```

**Resultado**
[Despliegue exitoso](https://dashboard.heroku.com/apps/decide-autenticacion/activity/releases/7c07b682-24bf-4389-adc9-f456a9fe418a)
Se comprueba que las traducciones están funcionando correctamente en la aplicación.
![image](https://user-images.githubusercontent.com/14946011/50974534-b949c380-14eb-11e9-839d-306996451275.png)

**Conclusión**
En la fase "release" de Heroku, todos los archivos creados mediante esos comandos no se mantienen. Es por esto que tuvimos problemas con el "makemigrations" en su momento, y la manera de crear superusuarios.
Por otra parte, todos los archivos creados directamente en desde el bash de la aplicación tampoco persisten como pudimos comprobar a la hora de crear superusuarios ([esto queda explicado en este comentario](https://github.com/decide-ganimedes-autenticacion/decide-ganimedes-autenticacion/issues/40#issuecomment-451473649))

Es por esto, que en la fase "web" del Procfile sí persisten, y por lo tanto funcionan correctamente las traducciones en la aplicación.

**Importante**
Cada módulo deberá añadir el _buildpack gettext_ tal como se ha mostrado en la Prueba 2 para que el comando "python manage.py compilemessages" funcione correctamente.
El buildpack que hemos utilizado para esta última prueba es el siguiente:
https://github.com/grauwoelfchen/heroku-buildpack-gettext.git

**Comment by davigldom** [comment]
Ya he replicado la incidencia y el comentario al repositorio padre de Decide-Ganímedes (decide-ganimedes/decide-ganimedes#75), y asignado a los coordinadores de los demás módulos.
