### ISSUE TITLE
Diseño único

### ISSUE THREAD

**Issue by davigldom** [decide-ganimedes-autenticacion/decide-ganimedes-autenticacion#9]
**[Incidencia replicada desde el repositorio padre de Decide-Ganímedes](https://github.com/decide-ganimedes/decide-ganimedes/issues/7)**

### Módulos implicados
Todos, aportando cada módulo un miembro de su equipo a un equipo de diseño común.

### Estado actual de la funcionalidad y qué se va a mejorar
Actualmente, la interfaz de la aplicación no posee ningún estilo de diseño, y se pretende añadirle un estilo uniforme.

### Cómo se quiere mejorar y el motivo
Crear hojas CSS para aplicar un estilo de diseño único entre todos los módulos de la aplicación Decide para aportar una vista de aplicación uniforme. 

### Resultado esperado
Una interfaz de la aplicación llamativa a la vista y con un diseño uniforme en todos los módulos.

### Alternativas consideradas
Para conseguir esto, podemos considerar lo siguiente:
- Utilizar un framework de diseño para sitios web como Bootstrap, Material Design...
- Crear una ruta/carpeta única para todos los módulos (grupos de decide) en los que estén los parámetros del diseño. Por ejemplo, podríamos crear una carpeta padre que se llame 'design' y dentro de esa carpeta crear una carpeta general para parametros de diseño generales y una carpeta por cada modulo para paginas únicas.

### Información adicional
No se requiere información adicional para esta incidencia.

**Comment by mrchavea** [comment]
Se da por finalizada al estar adaptado todo el estilo CSS según lo establecido.
