### ISSUE TITLE
Error de traducción al catalán en despliegue de Heroku

### ISSUE THREAD

**Issue by javirogo** [decide-ganimedes-autenticacion/decide-ganimedes-autenticacion#93]
**Incidencia para replicar en el repositorio padre de Decide-Ganímedes**

### Módulos implicados
Las traducciones se realizan en todos los módulos, por lo que todos los módulos están implicados.

### Descripción del error
Al finalizar el despliegue de Heroku, se ha detectado que uno de los idiomas no se traduce.

### Pasos para reproducir el error
1. Acceder a la página principal de la aplicación desplegada en Heroku.
2. Acceder a través del menú principal al registro de usuarios.
3. Cambiar de idioma al "Catalán"
4. Comprobar que los campos del formulario de registro no se traducen correctamente.

### Resultado obtenido

![image](https://user-images.githubusercontent.com/14946011/51062624-dc619980-15f7-11e9-82bb-c035e57ebb4c.png)

### Salida esperada
Se esperaba que todos los campos del formulario hubiesen sido traducidos al Catalán.

### Sistema operativo
Heroku utiliza docker en linux.

### Versión del software
El navegador utilizado es Chromium Version 71.0.3578.98 (Official Build) snap (64-bit).

### Información adicional
El log de despliegue no aporta ninguna información, ya que no devuelve errores de ningún tipo.
Se puede acceder a dicho log a través de [este enlace](https://dashboard.heroku.com/apps/ganimedes-authentication/activity/releases/4e9ae659-1816-4e45-97b9-8735527e3ecf).

**Comment by davigldom** [comment]
Se ha replicado la incidencia al repositorio padre de Decide-Ganímedes (decide-ganimedes/decide-ganimedes#81), y se han asignado a todos los coordinadores de los distintos módulos implicados en dicha incidencia.

**Comment by javirogo** [comment]
Tras una breve investigación del error, hemos descubierto un fallo en el archivo Procfile de nuestro repositorio.
Dicho fallo se producía al ejecutar el comando:
`python manage.py compilemessages -l es`
El cuál tan sólo compilaba las traducciones al español.

Para solucionarlo se ha optado por implementar, en lugar del comando anterior, el siguiente:
`python manage.py compilemessages`
Éste nos permite compilar todas las traducciones de todos los idiomas disponibles en la aplicación.

Una vez realizadas las pruebas oportunas se procede a integrar todos los cambios y subirlos al repositorio padre.

Esperando revisión para realizar el cierre de la incidencia.

**Comment by davigldom** [comment]
Tras revisar las traducciones al catalán en la aplicación para comprobar que dicho comando funcionaba correctamente al desplegar en Heroku, nos hemos percatado de que hay un mensaje que no se traduce, ni al catalán ni siquiera al español. Dicho mensaje es: "There are no ended votings yet", cuya traducción en los archivos "django.po" está como "", es decir, sin traducción. Dicho mensaje pertenece al módulo de visualización, pero como las traducciones se han implementado comúnmente, podríamos añadir nosotros el mensaje, junto a la actualización del Procfile. Adjunto captura:
![imagen](https://user-images.githubusercontent.com/34518143/51065826-2f8f1880-1607-11e9-9367-46a5d51203e7.png)

**Comment by javirogo** [comment]
Incidencia actualizada.
La traducción se ha agregado correctamente y se muestra el mensaje traducido en la aplicación.

Esperando revisión para realizar el cierre de la incidencia.

**Comment by javirogo** [comment]
Tras la aceptación y revisión de los cambios en el repositorio padre, se procede a cerrar la incidencia, quedando resuelto el problema planteado.
